// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ContactAssistantTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contactAssistant() {
    driver.get("https://www.ebay.ca/");
    driver.findElement(By.linkText("Help & Contact")).click();
    driver.findElement(By.id("helpBotChat")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, NaN);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#ohb_bBubble_2 > .hoverSource")));
    }
    driver.findElement(By.cssSelector(".ohb-btns-btn:nth-child(7)")).click();
    driver.findElement(By.cssSelector("#ohb-qr > button")).click();
    driver.findElement(By.id("ohb_ft_input")).click();
    driver.findElement(By.id("ohb_ft_input")).sendKeys("Hello");
    driver.findElement(By.id("ohb_ft_input")).sendKeys(Keys.ENTER);
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#ohb_ft_send_btn > i"));
      assert(elements.size() > 0);
    }
  }
}
